version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    privileged: true

    networks:
      - myweb

networks:
  myweb:
    driver: bridge
