# https://hub.docker.com/r/jenkins/jenkins/
# https://github.com/jenkinsci/docker/blob/master/README.md
# FROM jenkins/jenkins:lts-alpine
FROM jenkins/jenkins:lts
# FROM jenkins
USER root

EXPOSE 8080 50000
